<script setup lang="ts">
import {
  homeIcon,
  searchIcon,
  editIcon,
  folderIcon,
  plusIcon,
  checkIcon,
  closeIcon,
  trashIcon,
  settingsIcon,
  downloadIcon,
  importIcon,
  printIcon,
  historyIcon,
  webhookIcon,
  tagIcon,
  collapseIcon,
  moreIcon,
  calendarIcon,
  archiveIcon,
  categoryIcon,
  columns2Icon,
  columns3Icon,
  columns4Icon,
  pinIcon,
  pinFilledIcon,
  boldIcon,
  italicIcon,
  underlineIcon,
  strikethroughIcon,
  alignLeftIcon,
  alignCenterIcon,
  alignRightIcon,
  alignJustifyIcon,
  sendIcon,
  linkIcon,
  chevronDownIcon,
  listOrderedIcon,
  listUnorderedIcon,
  listCheckIcon,
  textColorIcon,
  highlightIcon,
  headingIcon,
  undoIcon,
  redoIcon,
} from "../assets/icons.ts";

const icons = {
  placeholder: homeIcon,
  home: homeIcon,
  search: searchIcon,
  edit: editIcon,
  folder: folderIcon,
  plus: plusIcon,
  check: checkIcon,
  close: closeIcon,
  trash: trashIcon,
  settings: settingsIcon,
  download: downloadIcon,
  import: importIcon,
  print: printIcon,
  history: historyIcon,
  webhook: webhookIcon,
  tag: tagIcon,
  collapse: collapseIcon,
  more: moreIcon,
  calendar: calendarIcon,
  archive: archiveIcon,
  category: categoryIcon,
  "columns-2": columns2Icon,
  "columns-3": columns3Icon,
  "columns-4": columns4Icon,
  pin: pinIcon,
  "pin-filled": pinFilledIcon,
  bold: boldIcon,
  italic: italicIcon,
  underline: underlineIcon,
  strikethrough: strikethroughIcon,
  "align-left": alignLeftIcon,
  "align-center": alignCenterIcon,
  "align-right": alignRightIcon,
  "align-justify": alignJustifyIcon,
  send: sendIcon,
  link: linkIcon,
  "chevron-down": chevronDownIcon,
  "list-ordered": listOrderedIcon,
  "list-unordered": listUnorderedIcon,
  "list-check": listCheckIcon,
  "text-color": textColorIcon,
  highlight: highlightIcon,
  heading: headingIcon,
  undo: undoIcon,
  redo: redoIcon,
};

const props = defineProps<{
  name: keyof typeof icons;
}>();
</script>

<template>
  <div v-html="icons[props.name]" class="icon flex-none aspect-square [&_svg]:w-full [&_svg]:h-full" aria-hidden="true" />
</template>
